# Generated by Django 5.2.15 on 2026-07-05 15:11

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='nome')),
                ('slug', models.SlugField(max_length=60, unique=True, verbose_name='slug')),
                ('endereco', models.CharField(blank=True, max_length=255, verbose_name='endereço')),
                ('cidade', models.CharField(default='Poços de Caldas', max_length=80, verbose_name='cidade')),
                ('estado', models.CharField(default='MG', max_length=2, verbose_name='UF')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='telefone')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'hotel',
                'verbose_name_plural': 'hotéis',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Hospede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=200, verbose_name='nome completo')),
                ('data_nascimento', models.DateField(verbose_name='data de nascimento')),
                ('documento', models.CharField(max_length=30, verbose_name='documento')),
                ('apartamento', models.CharField(max_length=20, verbose_name='apartamento')),
                ('data_checkin', models.DateField(default=datetime.date.today, verbose_name='data check-in')),
                ('data_checkout', models.DateField(blank=True, null=True, verbose_name='data check-out')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hospedes', to='core.hotel', verbose_name='hotel')),
            ],
            options={
                'verbose_name': 'hóspede',
                'verbose_name_plural': 'hóspedes',
                'ordering': ['-data_checkin', 'nome_completo'],
            },
        ),
        migrations.CreateModel(
            name='LocalAtividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='nome')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('capacidade_maxima', models.PositiveIntegerField(default=50, verbose_name='capacidade máxima')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locais', to='core.hotel', verbose_name='hotel')),
            ],
            options={
                'verbose_name': 'local de atividade',
                'verbose_name_plural': 'locais de atividade',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='nome')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('duracao_minutos', models.PositiveIntegerField(default=60, verbose_name='duração (min)')),
                ('capacidade_maxima', models.PositiveIntegerField(blank=True, help_text='Se vazio, usa a capacidade do local.', null=True, verbose_name='capacidade máxima')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atividades', to='core.hotel', verbose_name='hotel')),
                ('local_padrao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atividades_padrao', to='core.localatividade', verbose_name='local padrão')),
            ],
            options={
                'verbose_name': 'atividade',
                'verbose_name_plural': 'atividades',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='NoiteTematica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Domingo'), (1, 'Segunda-feira'), (2, 'Terça-feira'), (3, 'Quarta-feira'), (4, 'Quinta-feira'), (5, 'Sexta-feira'), (6, 'Sábado')], verbose_name='dia da semana')),
                ('tema', models.CharField(max_length=120, verbose_name='tema da noite')),
                ('cor_dominante', models.CharField(blank=True, max_length=40, verbose_name='cor dominante')),
                ('atracao_musical', models.CharField(max_length=200, verbose_name='atração musical')),
                ('vista_se', models.CharField(blank=True, max_length=200, verbose_name='vista-se')),
                ('descricao_gastronomia', models.TextField(verbose_name='gastronomia')),
                ('manha_tema', models.CharField(blank=True, max_length=200, verbose_name='tema da manhã')),
                ('manha_atividades', models.TextField(blank=True, verbose_name='atividades da manhã')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='noites_tematicas', to='core.hotel', verbose_name='hotel')),
            ],
            options={
                'verbose_name': 'noite temática',
                'verbose_name_plural': 'noites temáticas',
                'ordering': ['dia_semana'],
            },
        ),
        migrations.CreateModel(
            name='ProgramacaoDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='data')),
                ('hora_inicio', models.TimeField(verbose_name='início')),
                ('hora_fim', models.TimeField(verbose_name='término')),
                ('vagas_total', models.PositiveIntegerField(verbose_name='vagas totais')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programacoes', to='core.atividade', verbose_name='atividade')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programacoes', to='core.hotel', verbose_name='hotel')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programacoes', to='core.localatividade', verbose_name='local')),
            ],
            options={
                'verbose_name': 'programação diária',
                'verbose_name_plural': 'programações diárias',
                'ordering': ['data', 'hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='PresencaRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presente', models.BooleanField(default=True, verbose_name='presente')),
                ('registrado_em', models.DateTimeField(auto_now_add=True)),
                ('hospede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presencas', to='core.hospede', verbose_name='hóspede')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presencas_registradas', to=settings.AUTH_USER_MODEL, verbose_name='registrado por')),
                ('programacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presencas', to='core.programacaodiaria', verbose_name='programação')),
            ],
            options={
                'verbose_name': 'registro de presença',
                'verbose_name_plural': 'registros de presença',
            },
        ),
        migrations.CreateModel(
            name='InscricaoAtividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inscrito_em', models.DateTimeField(auto_now_add=True)),
                ('hospede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to='core.hospede', verbose_name='hóspede')),
                ('programacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to='core.programacaodiaria', verbose_name='programação')),
            ],
            options={
                'verbose_name': 'inscrição em atividade',
                'verbose_name_plural': 'inscrições em atividades',
            },
        ),
        migrations.CreateModel(
            name='Recreador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='nome')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='telefone')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recreadores', to='core.hotel', verbose_name='hotel')),
            ],
            options={
                'verbose_name': 'recreador',
                'verbose_name_plural': 'recreadores',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='programacaodiaria',
            name='recreador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programacoes', to='core.recreador', verbose_name='recreador'),
        ),
        migrations.AddIndex(
            model_name='hospede',
            index=models.Index(fields=['hotel', 'documento'], name='core_hosped_hotel_i_36740a_idx'),
        ),
        migrations.AddIndex(
            model_name='hospede',
            index=models.Index(fields=['hotel', 'data_checkout'], name='core_hosped_hotel_i_dff728_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='localatividade',
            unique_together={('hotel', 'nome')},
        ),
        migrations.AlterUniqueTogether(
            name='atividade',
            unique_together={('hotel', 'nome')},
        ),
        migrations.AlterUniqueTogether(
            name='noitetematica',
            unique_together={('hotel', 'dia_semana')},
        ),
        migrations.AlterUniqueTogether(
            name='presencaregistro',
            unique_together={('programacao', 'hospede')},
        ),
        migrations.AlterUniqueTogether(
            name='inscricaoatividade',
            unique_together={('programacao', 'hospede')},
        ),
        migrations.AlterUniqueTogether(
            name='programacaodiaria',
            unique_together={('hotel', 'data', 'hora_inicio', 'local')},
        ),
    ]
