# Generated by Django 5.2.15 on 2026-07-05 15:39

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProgramacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.SlugField(max_length=30, unique=True, verbose_name='código')),
                ('nome', models.CharField(max_length=80, verbose_name='nome')),
                ('idade_min', models.PositiveSmallIntegerField(verbose_name='idade mínima')),
                ('idade_max', models.PositiveSmallIntegerField(verbose_name='idade máxima')),
                ('cor', models.CharField(default='#1E6B43', max_length=7, verbose_name='cor')),
                ('icone', models.CharField(default='🌋', max_length=8, verbose_name='ícone')),
                ('ordem', models.PositiveSmallIntegerField(default=0, verbose_name='ordem')),
            ],
            options={
                'verbose_name': 'categoria de programação',
                'verbose_name_plural': 'categorias de programação',
                'ordering': ['ordem'],
            },
        ),
        migrations.AddField(
            model_name='atividade',
            name='frase_chamada',
            field=models.CharField(blank=True, max_length=200, verbose_name='frase de chamada'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='icone',
            field=models.CharField(default='⭐', max_length=8, verbose_name='ícone'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='cor_destaque',
            field=models.CharField(default='#FFD43D', max_length=7, verbose_name='cor destaque'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='cor_primaria',
            field=models.CharField(default='#1E6B43', max_length=7, verbose_name='cor primária'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='cor_secundaria',
            field=models.CharField(default='#2FAE63', max_length=7, verbose_name='cor secundária'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='rede_marca',
            field=models.CharField(choices=[('nacional_inn', 'Nacional Inn'), ('euro_suite', 'Euro Suite'), ('dan_inn', 'Dan Inn')], default='nacional_inn', max_length=20, verbose_name='rede / marca'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='slogan',
            field=models.CharField(blank=True, max_length=200, verbose_name='slogan'),
        ),
        migrations.AddField(
            model_name='noitetematica',
            name='cores_do_dia',
            field=models.CharField(blank=True, max_length=200, verbose_name='cores do dia'),
        ),
        migrations.AddField(
            model_name='noitetematica',
            name='horario_manha_fim',
            field=models.TimeField(default=datetime.time(10, 0), verbose_name='término manhã'),
        ),
        migrations.AddField(
            model_name='noitetematica',
            name='horario_manha_inicio',
            field=models.TimeField(default=datetime.time(8, 0), verbose_name='início manhã'),
        ),
        migrations.AddField(
            model_name='noitetematica',
            name='horario_noite_fim',
            field=models.TimeField(default=datetime.time(23, 0), verbose_name='término noite'),
        ),
        migrations.AddField(
            model_name='noitetematica',
            name='horario_noite_inicio',
            field=models.TimeField(default=datetime.time(19, 0), verbose_name='início noite'),
        ),
        migrations.AddField(
            model_name='noitetematica',
            name='manha_genero_musical',
            field=models.CharField(blank=True, max_length=200, verbose_name='música da manhã'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atividades', to='core.categoriaprogramacao', verbose_name='categoria'),
        ),
        migrations.AddField(
            model_name='programacaodiaria',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programacoes', to='core.categoriaprogramacao', verbose_name='categoria / faixa'),
        ),
        migrations.CreateModel(
            name='PassaporteHospede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('hospede', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='passaporte', to='core.hospede', verbose_name='hóspede')),
            ],
            options={
                'verbose_name': 'passaporte do hóspede',
                'verbose_name_plural': 'passaportes dos hóspedes',
            },
        ),
        migrations.CreateModel(
            name='ProdutoLoja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='nome')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('categoria', models.CharField(choices=[('acessorio', 'Acessório'), ('noite_tematica', 'Noite Temática'), ('souvenir', 'Souvenir')], default='acessorio', max_length=20, verbose_name='categoria')),
                ('cor_tema', models.CharField(blank=True, max_length=40, verbose_name='cor / tema')),
                ('preco', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='preço')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('ordem', models.PositiveSmallIntegerField(default=0, verbose_name='ordem')),
                ('hotel', models.ForeignKey(blank=True, help_text='Vazio = disponível em toda a rede.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='core.hotel', verbose_name='hotel')),
            ],
            options={
                'verbose_name': 'produto da loja',
                'verbose_name_plural': 'produtos da loja',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='CarimboPassaporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_conquista', models.DateField(default=datetime.date.today, verbose_name='data da conquista')),
                ('concedido_em', models.DateTimeField(auto_now_add=True)),
                ('noite_tematica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='carimbos', to='core.noitetematica', verbose_name='noite temática')),
                ('passaporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carimbos', to='core.passaportehospede', verbose_name='passaporte')),
            ],
            options={
                'verbose_name': 'carimbo do passaporte',
                'verbose_name_plural': 'carimbos do passaporte',
                'unique_together': {('passaporte', 'noite_tematica')},
            },
        ),
        migrations.CreateModel(
            name='Passeio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Domingo'), (1, 'Segunda-feira'), (2, 'Terça-feira'), (3, 'Quarta-feira'), (4, 'Quinta-feira'), (5, 'Sexta-feira'), (6, 'Sábado')], verbose_name='dia da semana')),
                ('titulo', models.CharField(max_length=120, verbose_name='título')),
                ('descricao', models.TextField(verbose_name='descrição')),
                ('ordem', models.PositiveSmallIntegerField(default=0, verbose_name='ordem')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passeios', to='core.hotel', verbose_name='hotel')),
            ],
            options={
                'verbose_name': 'passeio',
                'verbose_name_plural': 'passeios',
                'ordering': ['dia_semana', 'ordem'],
                'unique_together': {('hotel', 'dia_semana', 'titulo')},
            },
        ),
    ]
