# Generated by Django 5.2.15 on 2026-07-05 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_categoriaprogramacao_atividade_frase_chamada_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriaprogramacao',
            options={'ordering': ['ordem'], 'verbose_name': 'faixa etária / categoria', 'verbose_name_plural': 'faixas etárias / categorias'},
        ),
        migrations.AddField(
            model_name='categoriaprogramacao',
            name='descricao_atividades',
            field=models.TextField(blank=True, help_text='Tipos de atividades desta faixa (ex.: caça ao tesouro, gincanas).', verbose_name='atividades típicas'),
        ),
    ]
