# Generated by Django 5.2.15 on 2026-07-05 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_categoriaprogramacao_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaReuniao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='nome da sala')),
                ('slug', models.SlugField(max_length=80, unique=True, verbose_name='slug')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('jitsi_room', models.CharField(blank=True, max_length=120, verbose_name='sala Jitsi')),
                ('ativa', models.BooleanField(default=True, verbose_name='ativa')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('hotel', models.ForeignKey(blank=True, help_text='Vazio = sala da rede (todos os diretores).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salas_reuniao', to='core.hotel', verbose_name='hotel')),
            ],
            options={
                'verbose_name': 'sala de reunião',
                'verbose_name_plural': 'salas de reunião',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='MensagemReuniao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(max_length=2000, verbose_name='mensagem')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensagens_reuniao', to=settings.AUTH_USER_MODEL, verbose_name='autor')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='core.salareuniao', verbose_name='sala')),
            ],
            options={
                'verbose_name': 'mensagem da reunião',
                'verbose_name_plural': 'mensagens da reunião',
                'ordering': ['criado_em'],
            },
        ),
    ]
