# Generated by Django 5.2.15 on 2026-07-05 16:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_salareuniao_mensagemreuniao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papel', models.CharField(choices=[('ADMIN', 'Administrador'), ('DIRETOR', 'Diretor'), ('GERENTE', 'Gerente'), ('SUPERVISOR', 'Supervisor'), ('RECREADOR', 'Recreador'), ('RECEPCAO', 'Recepção'), ('RESTAURANTE', 'Restaurante'), ('LOJA', 'Loja')], default='RECEPCAO', max_length=20, verbose_name='papel')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('hotel', models.ForeignKey(blank=True, help_text='Vazio = acesso a todos os hotéis (Administrador/Diretor).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfis', to='core.hotel', verbose_name='hotel')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'perfil de usuário',
                'verbose_name_plural': 'perfis de usuário',
            },
        ),
    ]
