# Generated by Django 5.2.15 on 2026-07-05 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_criar_grupos'),
    ]

    operations = [
        migrations.AddField(
            model_name='passaportehospede',
            name='moedas',
            field=models.PositiveIntegerField(default=0, verbose_name='moedas Vulcãozinho'),
        ),
        migrations.AddField(
            model_name='produtoloja',
            name='codigo_qr',
            field=models.SlugField(blank=True, help_text='Gerado automaticamente se vazio.', max_length=40, null=True, unique=True, verbose_name='código QR'),
        ),
        migrations.AddField(
            model_name='produtoloja',
            name='estoque',
            field=models.PositiveIntegerField(default=0, verbose_name='estoque'),
        ),
    ]
