# Generated by Django 5.2.15 on 2026-07-06 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_financeiro_margem'),
    ]

    operations = [
        migrations.AddField(
            model_name='programacaodiaria',
            name='atividade_chuva',
            field=models.CharField(blank=True, max_length=200, verbose_name='atividade (plano B chuva)'),
        ),
        migrations.AddField(
            model_name='programacaodiaria',
            name='auditado_por',
            field=models.CharField(blank=True, max_length=120, verbose_name='auditado por'),
        ),
        migrations.AddField(
            model_name='programacaodiaria',
            name='coordenador_nome',
            field=models.CharField(blank=True, max_length=120, verbose_name='coordenador'),
        ),
        migrations.AddField(
            model_name='programacaodiaria',
            name='local_chuva_nome',
            field=models.CharField(blank=True, max_length=200, verbose_name='local chuva'),
        ),
        migrations.AddField(
            model_name='programacaodiaria',
            name='musico_nome',
            field=models.CharField(blank=True, max_length=120, verbose_name='músico'),
        ),
        migrations.AddField(
            model_name='programacaodiaria',
            name='realizado',
            field=models.BooleanField(default=False, verbose_name='realizado'),
        ),
        migrations.AddField(
            model_name='programacaodiaria',
            name='responsavel_nome',
            field=models.CharField(blank=True, max_length=120, verbose_name='responsável'),
        ),
        migrations.CreateModel(
            name='EventoRecreacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pacote', models.CharField(blank=True, max_length=80, verbose_name='pacote / tema')),
                ('mes_referencia', models.CharField(blank=True, max_length=40, verbose_name='mês referência')),
                ('nome', models.CharField(max_length=200, verbose_name='evento')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('tipo_servico', models.CharField(blank=True, max_length=80, verbose_name='tipo serviço / fornecedor')),
                ('nivel_atracao', models.CharField(blank=True, max_length=60, verbose_name='nível atração')),
                ('contrato_assinado', models.CharField(blank=True, max_length=40, verbose_name='contrato assinado')),
                ('prestador', models.CharField(blank=True, max_length=120, verbose_name='prestador / fornecedor')),
                ('responsavel', models.CharField(blank=True, max_length=120, verbose_name='responsável')),
                ('dia_semana', models.CharField(blank=True, max_length=20, verbose_name='dia da semana')),
                ('data_inicio', models.DateField(verbose_name='data inicial')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='data final')),
                ('orcamento', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='orçamento (R$)')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('agendado', 'Agendado'), ('realizado', 'Realizado'), ('cancelado', 'Cancelado'), ('nao_autorizado', 'Não autorizado')], default='agendado', max_length=20, verbose_name='status')),
                ('importado_em', models.DateTimeField(auto_now_add=True, verbose_name='importado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos_recreacao', to='core.hotel', verbose_name='hotel')),
            ],
            options={
                'verbose_name': 'evento de recreação',
                'verbose_name_plural': 'eventos de recreação',
                'ordering': ['data_inicio', 'nome'],
                'indexes': [models.Index(fields=['hotel', 'data_inicio'], name='core_evento_hotel_i_fcf523_idx')],
            },
        ),
    ]
