# Generated by Django 5.2.15 on 2026-07-07 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_telao_grade_publicada'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospede',
            name='responsavel_assinado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='assinado em'),
        ),
        migrations.AddField(
            model_name='hospede',
            name='responsavel_assinatura',
            field=models.TextField(blank=True, help_text='Imagem da assinatura capturada no check-in (data URL PNG).', verbose_name='assinatura do responsável'),
        ),
        migrations.AddField(
            model_name='hospede',
            name='responsavel_documento',
            field=models.CharField(blank=True, max_length=30, verbose_name='documento do responsável'),
        ),
        migrations.AddField(
            model_name='hospede',
            name='responsavel_nome',
            field=models.CharField(blank=True, max_length=200, verbose_name='nome do responsável'),
        ),
        migrations.AddField(
            model_name='hospede',
            name='responsavel_parentesco',
            field=models.CharField(blank=True, max_length=40, verbose_name='parentesco'),
        ),
        migrations.AddField(
            model_name='hospede',
            name='responsavel_telefone',
            field=models.CharField(blank=True, max_length=30, verbose_name='telefone do responsável'),
        ),
    ]
