# Generated by Django 5.2.15 on 2026-07-07 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_hospede_responsavel_assinado_em_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospede',
            name='responsavel_parentesco',
            field=models.CharField(blank=True, choices=[('mae', 'Mãe'), ('pai', 'Pai'), ('avo', 'Avô/Avó'), ('tio', 'Tio/Tia'), ('responsavel_legal', 'Responsável legal'), ('outro', 'Outro')], max_length=40, verbose_name='parentesco'),
        ),
    ]
