# Generated by Django 5.2.15 on 2026-07-07 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_hospede_responsavel_parentesco'),
    ]

    operations = [
        migrations.AddField(
            model_name='passeio',
            name='hora_retorno',
            field=models.TimeField(blank=True, null=True, verbose_name='horário de retorno'),
        ),
        migrations.AddField(
            model_name='passeio',
            name='hora_saida',
            field=models.TimeField(blank=True, null=True, verbose_name='horário de saída'),
        ),
        migrations.AddField(
            model_name='passeio',
            name='ponto_encontro',
            field=models.CharField(blank=True, max_length=160, verbose_name='ponto de encontro'),
        ),
        migrations.AddField(
            model_name='passeio',
            name='preco',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Deixe em branco para passeio gratuito / incluso.', max_digits=8, null=True, verbose_name='preço (R$)'),
        ),
        migrations.AddField(
            model_name='passeio',
            name='vagas',
            field=models.PositiveSmallIntegerField(default=0, help_text='0 = sem limite de vagas.', verbose_name='vagas'),
        ),
        migrations.CreateModel(
            name='InscricaoPasseio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='data do passeio')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('hospede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes_passeio', to='core.hospede', verbose_name='hóspede')),
                ('passeio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to='core.passeio', verbose_name='passeio')),
            ],
            options={
                'verbose_name': 'inscrição em passeio',
                'verbose_name_plural': 'inscrições em passeios',
                'ordering': ['-data', 'passeio__ordem'],
                'indexes': [models.Index(fields=['passeio', 'data'], name='core_inscri_passeio_0d52d5_idx')],
                'unique_together': {('passeio', 'hospede', 'data')},
            },
        ),
    ]
