# Generated by Django 5.2.15 on 2026-07-07 14:08

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_passeio_hora_retorno_passeio_hora_saida_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='pix_beneficiario',
            field=models.CharField(blank=True, max_length=80, verbose_name='nome do beneficiário PIX'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='pix_chave',
            field=models.CharField(blank=True, help_text='CPF/CNPJ, e-mail, telefone ou chave aleatória para receber pagamentos de passeios.', max_length=140, verbose_name='chave PIX'),
        ),
        migrations.AddField(
            model_name='inscricaopasseio',
            name='comprovante',
            field=models.FileField(blank=True, null=True, upload_to=core.models.comprovante_upload_path, verbose_name='comprovante de pagamento'),
        ),
        migrations.AddField(
            model_name='inscricaopasseio',
            name='comprovante_enviado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='comprovante enviado em'),
        ),
        migrations.AddField(
            model_name='inscricaopasseio',
            name='pagamento_confirmado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='pagamento confirmado em'),
        ),
        migrations.AddField(
            model_name='inscricaopasseio',
            name='pagamento_confirmado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagamentos_passeio_confirmados', to=settings.AUTH_USER_MODEL, verbose_name='confirmado por'),
        ),
        migrations.AddField(
            model_name='inscricaopasseio',
            name='status_pagamento',
            field=models.CharField(choices=[('isento', 'Incluso / gratuito'), ('pendente', 'Aguardando pagamento'), ('comprovante_enviado', 'Comprovante enviado'), ('confirmado', 'Pagamento confirmado'), ('rejeitado', 'Comprovante rejeitado')], default='pendente', max_length=25, verbose_name='status do pagamento'),
        ),
        migrations.AddField(
            model_name='inscricaopasseio',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='valor (R$)'),
        ),
        migrations.AddIndex(
            model_name='inscricaopasseio',
            index=models.Index(fields=['status_pagamento'], name='core_inscri_status__940847_idx'),
        ),
    ]
