# Generated by Django 5.2.15 on 2026-07-07 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_hotel_pix_beneficiario_hotel_pix_chave_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passeio',
            name='pix_beneficiario',
            field=models.CharField(blank=True, max_length=80, verbose_name='beneficiário PIX do passeio'),
        ),
        migrations.AddField(
            model_name='passeio',
            name='pix_chave',
            field=models.CharField(blank=True, help_text='Opcional. Se vazio, usa a chave PIX do hotel.', max_length=140, verbose_name='chave PIX do passeio'),
        ),
    ]
