# Generated by Django 5.2.15 on 2026-07-15 13:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_hotel_whatsapp_setor_pagamentos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recreador',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='recreadores/%Y/%m/', verbose_name='foto'),
        ),
        migrations.AddField(
            model_name='recreador',
            name='pin_atualizado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='PIN atualizado em'),
        ),
        migrations.AddField(
            model_name='recreador',
            name='pin_hash',
            field=models.CharField(blank=True, max_length=128, verbose_name='PIN (hash)'),
        ),
        migrations.CreateModel(
            name='PontoBatida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída')], max_length=10, verbose_name='tipo')),
                ('extra_plantao', models.BooleanField(default=False, verbose_name='extra / plantão')),
                ('registrado_em', models.DateTimeField(default=django.utils.timezone.now, verbose_name='registrado em')),
                ('foto_auditoria', models.ImageField(blank=True, null=True, upload_to='ponto/%Y/%m/', verbose_name='foto da batida')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.CharField(blank=True, max_length=255, verbose_name='user agent')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ponto_batidas', to='core.hotel', verbose_name='hotel')),
                ('recreador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ponto_batidas', to='core.recreador', verbose_name='recreador')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ponto_batidas_registradas', to=settings.AUTH_USER_MODEL, verbose_name='registrado por')),
            ],
            options={
                'verbose_name': 'batida de ponto',
                'verbose_name_plural': 'batidas de ponto',
                'ordering': ['-registrado_em'],
                'indexes': [models.Index(fields=['hotel', 'registrado_em'], name='core_pontob_hotel_i_2e7a1b_idx'), models.Index(fields=['recreador', 'registrado_em'], name='core_pontob_recread_982cc4_idx')],
            },
        ),
    ]
