# Generated by Django 5.2.15 on 2026-07-15 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_ponto_recreadores'),
    ]

    operations = [
        migrations.AddField(
            model_name='recreador',
            name='face_descriptor',
            field=models.JSONField(blank=True, help_text='Vetor 128-D gerado no cadastro da foto para reconhecimento.', null=True, verbose_name='descritor facial'),
        ),
    ]
