# Generated by Django 5.2.15 on 2026-07-16 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_ponto_face_descriptor'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoredMediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=500, unique=True, verbose_name='caminho')),
                ('content', models.BinaryField(verbose_name='conteúdo')),
                ('content_type', models.CharField(default='application/octet-stream', max_length=120, verbose_name='content-type')),
                ('size', models.PositiveIntegerField(default=0, verbose_name='tamanho')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'arquivo de mídia',
                'verbose_name_plural': 'arquivos de mídia',
                'ordering': ['-criado_em'],
            },
        ),
    ]
